//#include "Dialogs\store.hpp"
#include "Dialogs\common.hpp" //must be on top
#include "Dialogs\phone.hpp"
#include "Dialogs\phone_contacts.hpp"
#include "Dialogs\phone_contactsadd.hpp"
#include "Dialogs\phone_messages.hpp"
#include "Dialogs\phone_message_new.hpp"
#include "Dialogs\phone_last_calls.hpp"
#include "Dialogs\phone_change_sim.hpp"
#include "Dialogs\phone_customize.hpp"
#include "Dialogs\phone_add_founds.hpp"
#include "Dialogs\phone_services.hpp"
