#include "Dialogs\main.hpp"
#include "Dialogs\computer_add_profile.hpp"
#include "Dialogs\computer_add_vehicle.hpp"
#include "Dialogs\computer_check_profile.hpp"
#include "Dialogs\computer_check_vehicle.hpp"
#include "Dialogs\computer_main.hpp"
#include "Dialogs\computer_view_case_profile.hpp"
#include "Dialogs\computer_view_case_vehicle.hpp"
