["onTick", true] call Client_fnc_eventRegister;
["onSave", true] call Client_fnc_eventRegister;
["onVechicleTake"] call Client_fnc_eventRegister;
["onMoneyGive"] call Client_fnc_eventRegister;
["onMoneyTake"] call Client_fnc_eventRegister;
["onMoneyWithdraw"] call Client_fnc_eventRegister;
["onPlayerFirstConnect"] call Client_fnc_eventRegister;
["onPlayerProfileChange"] call Client_fnc_eventRegister;
["onVehicleSpawn"] call Client_fnc_eventRegister;
["onFactionWorkingChange"] call Client_fnc_eventRegister;
["onFactionWorkingStart"] call Client_fnc_eventRegister;
["onFactionWorkingStop"] call Client_fnc_eventRegister;
